- include: firewall.yml

- name: APT | Update
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: APT | Install OpenVPN
  apt:
    name: openvpn
    state: present

- name: FILE | Create /etc/openvpn
  file:
    path: /etc/openvpn
    state: directory
    mode: 0755
    owner: root
    group: root

- name: FILE | Create /etc/openvpn/keys
  file:
    path: /etc/openvpn/keys
    state: directory
    mode: 0700
    owner: root
    group: root

- name: FILE | Create clientside and serverside directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ clientside }}/keys"
    - "{{ serverside }}"
  become: true
  become_user: "{{ user }}"

- name: TEMPLATE | Create openvpn base client.conf
  template:
    src: client.conf.j2
    dest: "{{ clientside }}/client.conf"
    owner: root
    group: root
    mode: 0644

- name: GET URL | Download EasyRSA
  get_url:
    url: "{{ easyrsa_url }}"
    dest: "/home/{{ user }}/openvpn"
  become: true
  become_user: "{{ user }}"

- name: TEMPLATE | Create scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ user }}/openvpn/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - create_serverside
    - create_clientside
  tags: client

- name: COMMAND | Run serverside script
  command: ./create_serverside
  args:
    chdir: "/home/{{ user }}/openvpn"
    creates: "{{ easyrsa_server }}/ta.key"
  become: true
  become_user: "{{ user }}"

- name: COMMAND | Run clientside script
  command: ./create_clientside {{ item }}
  args:
    chdir: "/home/{{ user }}/openvpn"
    creates: "{{ clientside }}/files/{{ item }}.ovpn"
  become: true
  become_user: "{{ user }}"
  loop: "{{ openvpn_clients }}"
  tags: client

- name: COMMAND | Install all server keys
  command: install -o root -g root -m 600 {{ item.name }} /etc/openvpn/keys/
  args:
    chdir: "{{ item.path }}"
    creates: "/etc/openvpn/keys/{{ item.name }}"
  loop:
    - name: "ca.crt"
      path: "{{ easyrsa_server }}/pki"
    - name: "{{ ansible_hostname }}.crt"
      path: "{{ easyrsa_server }}/pki/issued"
    - name: "{{ ansible_hostname }}.key"
      path: "{{ easyrsa_server }}/pki/private"
    - name: "ta.key"
      path: "{{ easyrsa_server }}"

- name: COPY | Copy Diffie-Hellman key
  copy:
    src: "{{ openvpn_dh }}"
    dest: /etc/openvpn/keys/dh.pem
    owner: root
    group: root
    mode: 0600

- name: TEMPLATE | Create openvpn server.conf
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644
  notify: restart openvpn

- name: SYSTEMD | Make sure openvpn is started and enabled
  systemd:
    name: openvpn
    state: started
    enabled: true
