- name: Create Jackett group
  group:
    name: "{{ jackett_group_name }}"
    system: true
    state: present

- name: Create Jackett user
  user:
    name: "{{ jackett_user_name }}"
    group: "{{ jackett_group_name }}"
    home: "{{ jackett_user_home }}"
    state: present

- name: Create Jackett bin directory
  file:
    dest: "{{ jackett_user_home }}/bin"
    owner: "{{ jackett_user_name }}"
    group: "{{ jackett_group_name }}"
    state: directory

- name: Find latest Jackett release
  shell: curl -s https://api.github.com/repos/Jackett/Jackett/releases/latest | grep Jackett.Binaries.Mono | grep browser_download_url | cut -d \" -f 4
  register: jackett_release_url

- name: Download and unpack Jackett
  unarchive:
    src: "{{ jackett_release_url.stdout }}"
    dest: "{{ jackett_user_home }}/bin/"
    remote_src: true

- name: Set permissions for Jackett
  file:
    dest: "{{ jackett_user_home }}/bin"
    owner: "{{ jackett_user_name }}"
    state: directory
    recurse: true

- name: Add Jackett service
  template:
    src: jackett.service.j2
    dest: /etc/systemd/system/jackett.service
    owner: root
    group: root

- name: Start Jackett on startup
  service:
    name: jackett
    state: started
    enabled: true
