- name: Add Plex apt key
  become: true
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Add Plex repository
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present
  register: plex_repo_added

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Update apt
  apt:
    update_cache: yes
  when: plex_repo_added.changed

- name: Install plexmediaserver
  apt:
    name: plexmediaserver
    state: present
  register: plexmediaserver_installed

- name: Restart plexmediaserver
  service:
    name: plexmediaserver
    state: restarted
  when: plexmediaserver_installed.changed
