- name: Install apt Dependencies
  apt:
    name: "{{ ddclient_apt_install }}"
    state: present
  become: true

- name: Copy over ddclient Executable
  synchronize:
    src: "{{ ddclient_git_repo_dest }}/ddclient.in"
    dest: "{{ ddclient_exec }}"
    checksum: yes
    times: no
  delegate_to: "{{ inventory_hostname }}"
  when: _ddclient_git_cloned.changed
  become: true

- name: Create configuration, cache, and run directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - "{{ ddclient_file.directory }}"
    - "{{ ddclient_cache }}"
    - "{{ ddclient_pid.directory }}"
  become: true

- name: Create Systemd File
  template:
    src: ddclient.service.j2
    dest: /etc/systemd/system/ddclient.service
    owner: root
    group: root
  become: true
