- name: APT | Update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - upgrade_packages

- name: APT | Upgrade all packages
  apt:
    upgrade: dist
  tags:
    - upgrade_packages
