- name: APT | Install/update vim
  apt:
    name: vim
    state: latest

- name: COPY | Update vimrc
  copy:
    src: vimrc
    dest: /home/{{ ansible_user }}/.vimrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
