- hosts: grafanapi
  become: true

  roles:
    - { role: influxdb, tags: [ 'influxdb' ] }
    - { role: telegraf, tags: [ 'telegraf' ] }
    - { role: grafana, tags: [ 'grafana' ] }

  handlers:
    - name: restart influxdb
      command: /etc/init.d/influxdb restart

    - name: restart grafana
      command: /etc/init.d/grafana-server restart
