- name: Install OpenVPN
  become: true
  apt:
    name: openvpn
    state: present

- name: Copy Mullvad certificate and configuration
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: mullvad_ca.crt, dest: /etc/openvpn/mullvad_ca.crt }
    - { src: "{{ mullvad_conf_file_path }}", dest: /etc/openvpn/mullvad.conf }

- name: Add Mullvad credentials
  become: true
  template:
    src: mullvad_userpass.txt.j2
    dest: /etc/openvpn/mullvad_userpass.txt
  notify: restart openvpn
