- name: Create docker-wireguard home
  file:
    path: "{{ docker_wireguard_home }}"
    state: directory

- name: Start docker-wireguard contianer
  docker_container:
    image: linuxserver/wireguard:latest
    name: wireguard
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    env:
      TZ: Etc/UTC
      SERVERURL: "{{ wireguard_server_url }}"
      PEERS: "{{ wireguard_server_peers | int }}"
      PUID: "{{ ansible_user_uid | int }}"
      PGID: "{{ ansible_user_gid | int }}"

    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker_wireguard_home }}/config:/config"
      - "/lib/modules:/lib/modules"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
