- hosts: plexpi
  become: true

  roles:
    - { role: raspbian, tags: [ 'raspbian' ] }
    - { role: vim, tags: [ 'vim' ] }
    - { role: htop, tags: [ 'htop' ] }
    - { role: plexmediaserver, tags: [ 'plexmediaserver' ] }
